import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import type { GrottoConfig } from "./config.js";

/** Constant-time string compare (hash first so lengths always match). */
export function safeEq(a: string, b: string): boolean {
  const ha = crypto.createHash("sha256").update(a).digest();
  const hb = crypto.createHash("sha256").update(b).digest();
  return crypto.timingSafeEqual(ha, hb);
}

// ── TOTP (RFC 6238: HMAC-SHA1, 6 digits, 30s period) ───────────────────────

const B32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
const PERIOD = 30;

export function base32Encode(buf: Buffer): string {
  let bits = 0;
  let value = 0;
  let out = "";
  for (const byte of buf) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      out += B32[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) out += B32[(value << (5 - bits)) & 31];
  return out;
}

function base32Decode(s: string): Buffer {
  let bits = 0;
  let value = 0;
  const out: number[] = [];
  for (const ch of s.toUpperCase()) {
    const idx = B32.indexOf(ch);
    if (idx === -1) continue;
    value = (value << 5) | idx;
    bits += 5;
    if (bits >= 8) {
      out.push((value >>> (bits - 8)) & 0xff);
      bits -= 8;
    }
  }
  return Buffer.from(out);
}

function hotp(secret: Buffer, counter: number): string {
  const msg = Buffer.alloc(8);
  msg.writeBigUInt64BE(BigInt(counter));
  const h = crypto.createHmac("sha1", secret).update(msg).digest();
  const off = h[h.length - 1] & 0xf;
  const code =
    (((h[off] & 0x7f) << 24) | (h[off + 1] << 16) | (h[off + 2] << 8) | h[off + 3]) %
    1_000_000;
  return String(code).padStart(6, "0");
}

interface MfaState {
  secret: string; // base32
  lastCounter: number; // replay protection: each code spends its time-step
}

export class Mfa {
  private file: string;
  /** Secret generated by setup, not yet confirmed with a valid code. */
  private pending: string | null = null;

  constructor(cfg: GrottoConfig) {
    this.file = path.join(cfg.home, "mfa.json");
  }

  private read(): MfaState | null {
    try {
      const s = JSON.parse(fs.readFileSync(this.file, "utf8")) as MfaState;
      return typeof s.secret === "string" && s.secret.length >= 16 ? s : null;
    } catch {
      return null;
    }
  }

  enabled(): boolean {
    return this.read() !== null;
  }

  /** Start enrollment: returns the secret + otpauth URI for the authenticator. */
  setup(): { secret: string; otpauth: string } {
    this.pending = base32Encode(crypto.randomBytes(20));
    const otpauth =
      `otpauth://totp/Development%20Intelligence?secret=${this.pending}` +
      `&issuer=Development%20Intelligence&algorithm=SHA1&digits=6&period=${PERIOD}`;
    return { secret: this.pending, otpauth };
  }

  /** Confirm enrollment with a code from the authenticator. */
  enable(code: string): boolean {
    if (!this.pending) return false;
    const counter = this.matchCounter(this.pending, code, -1);
    if (counter === null) return false;
    const state: MfaState = { secret: this.pending, lastCounter: counter };
    fs.writeFileSync(this.file, JSON.stringify(state), { mode: 0o600 });
    this.pending = null;
    return true;
  }

  disable(code: string): boolean {
    if (!this.verify(code)) return false;
    fs.rmSync(this.file, { force: true });
    return true;
  }

  /** Verify a login code; accepts ±1 time-step, never a spent counter. */
  verify(code: string): boolean {
    const state = this.read();
    if (!state) return false;
    const counter = this.matchCounter(state.secret, code, state.lastCounter);
    if (counter === null) return false;
    fs.writeFileSync(this.file, JSON.stringify({ ...state, lastCounter: counter }), {
      mode: 0o600,
    });
    return true;
  }

  private matchCounter(secret: string, code: string, lastCounter: number): number | null {
    if (!/^\d{6}$/.test(code)) return null;
    const key = base32Decode(secret);
    const now = Math.floor(Date.now() / 1000 / PERIOD);
    for (const delta of [0, -1, 1]) {
      const counter = now + delta;
      if (counter <= lastCounter) continue;
      if (safeEq(hotp(key, counter), code)) return counter;
    }
    return null;
  }
}

// ── Device credentials (issued at login, revocable, expiring) ───────────────

const LOGIN_TTL_MS = 30 * 24 * 3600 * 1000;
const MAX_LOGINS = 20;

interface LoginEntry {
  hash: string; // sha256 of the credential — a leaked file can't log in
  createdAt: number;
  expiresAt: number;
}

export class Logins {
  private file: string;
  private entries: LoginEntry[] = [];

  constructor(cfg: GrottoConfig) {
    this.file = path.join(cfg.home, "logins.json");
    try {
      const raw = JSON.parse(fs.readFileSync(this.file, "utf8")) as LoginEntry[];
      if (Array.isArray(raw)) this.entries = raw.filter((e) => e?.hash);
    } catch {
      /* fresh store */
    }
    this.prune();
  }

  private hash(credential: string): string {
    return crypto.createHash("sha256").update(credential).digest("hex");
  }

  private prune(): void {
    const now = Date.now();
    this.entries = this.entries
      .filter((e) => e.expiresAt > now)
      .sort((a, b) => b.createdAt - a.createdAt)
      .slice(0, MAX_LOGINS);
  }

  private save(): void {
    try {
      const tmp = this.file + ".tmp";
      fs.writeFileSync(tmp, JSON.stringify(this.entries), { mode: 0o600 });
      fs.renameSync(tmp, this.file);
    } catch {
      /* best-effort */
    }
  }

  issue(): { credential: string; expiresAt: number } {
    const credential = crypto.randomBytes(32).toString("base64url");
    const expiresAt = Date.now() + LOGIN_TTL_MS;
    this.entries.push({ hash: this.hash(credential), createdAt: Date.now(), expiresAt });
    this.prune();
    this.save();
    return { credential, expiresAt };
  }

  verify(credential: string): boolean {
    const h = this.hash(credential);
    const now = Date.now();
    return this.entries.some((e) => e.expiresAt > now && safeEq(e.hash, h));
  }

  revoke(credential: string): void {
    const h = this.hash(credential);
    this.entries = this.entries.filter((e) => !safeEq(e.hash, h));
    this.save();
  }
}

// ── Login throttle (slows TOTP/token brute force; single-user scale) ───────

const WINDOW_MS = 15 * 60 * 1000;
const MAX_FAILURES = 8;

export class LoginThrottle {
  private failures: number[] = [];

  locked(): boolean {
    const cutoff = Date.now() - WINDOW_MS;
    this.failures = this.failures.filter((t) => t > cutoff);
    return this.failures.length >= MAX_FAILURES;
  }

  /** Seconds until the oldest counted failure ages out — drives the UI countdown. */
  retryAfter(): number {
    if (!this.locked()) return 0;
    const oldest = this.failures[this.failures.length - MAX_FAILURES];
    return Math.max(1, Math.ceil((oldest + WINDOW_MS - Date.now()) / 1000));
  }

  attemptsLeft(): number {
    const cutoff = Date.now() - WINDOW_MS;
    this.failures = this.failures.filter((t) => t > cutoff);
    return Math.max(0, MAX_FAILURES - this.failures.length);
  }

  fail(): void {
    this.failures.push(Date.now());
  }
}
